version: '3.7'

x-defaults: &defaults
  restart: always
  init: true

  env_file:
    - .env

  environment: &environment
    DOCKER: true
    NODE_ENV: production
    REDIS_HOST: redis
    REDIS_PORT: 6379
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432

  logging:
    driver: 'json-file'
    options:
      max-size: '5m'
      max-file: '10'
      tag: '{{.Name}}'

services:
  postgres:
    <<: *defaults
    image: postgres:15.2
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    <<: *defaults
    image: redis:7.2-alpine
    volumes:
      - ./data/redis:/data

  api:
    <<: *defaults
    image: ghcr.io/decouvrebitcoin/sovereign-university-api:${IMAGE_TAG}
    environment:
      <<: *environment
      HOST: 0.0.0.0
      PORT: 3000
    expose:
      - 3000
    volumes:
      - ./data/cdn:$CDN_PATH
      - ./data/sync:$SYNC_PATH
    labels:
      - traefik.enable=true
      - traefik.http.routers.university-api-${ENV}.rule=Host(`api.${DOMAIN}`)
      - traefik.http.routers.university-api-${ENV}.entrypoints=https,http
      - traefik.http.routers.university-api-${ENV}.tls=true
      - traefik.http.routers.university-api-${ENV}.tls.certresolver=security
      - traefik.http.services.university-api-${ENV}.loadbalancer.server.port=3000
      - traefik.http.routers.university-api-${ENV}.service=university-api-${ENV}
    depends_on:
      - postgres

  cdn:
    <<: *defaults
    image: nginx:latest
    volumes:
      - ./cdn/nginx.conf:/etc/nginx/nginx.conf
      - ./data/cdn:/var/www/cdn
    labels:
      - traefik.enable=true
      - traefik.http.routers.university-cdn-${ENV}.rule=Host(`cdn.${DOMAIN}`)
      - traefik.http.routers.university-cdn-${ENV}.entrypoints=https,http
      - traefik.http.routers.university-cdn-${ENV}.tls=true
      - traefik.http.routers.university-cdn-${ENV}.tls.certresolver=security
      - traefik.http.middlewares.university-cdn-${ENV}.compress=true

  web:
    <<: *defaults
    image: ghcr.io/decouvrebitcoin/sovereign-university-web:${IMAGE_TAG}
    labels:
      - traefik.enable=true
      - traefik.http.routers.university-web-${ENV}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.university-web-${ENV}.entrypoints=https,http
      - traefik.http.routers.university-web-${ENV}.tls=true
      - traefik.http.routers.university-web-${ENV}.tls.certresolver=security
      - traefik.http.middlewares.university-web-${ENV}.compress=true

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true
